application: what-2-wear
version: 4
api_version: 1
runtime: python

handlers:
- url: /my_images
  static_dir: my_images
- url: /my_csv_file
  static_dir: my_csv_file
- url: /loadImages
  script: my_loader.py
  login: admin
- url: /.*
  script: server_side.py

builtins:
- datastore_admin: on