application: what-2-wear
version: 23
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static

- url: /my_images
  static_dir: my_images
  
  
- url: /(loadData|clearAllData|load-page|clear-page)
  script: data_handler.py
  login: admin

- url: /(view-content|delete|imagesJson)
  script: admin_site.py
  login: admin

- url: /
  script: main.py
  login: admin

- url: /.*
  script: main.py

builtins:
- datastore_admin: on